---
- name: Install zabbix agent CentOS
  hosts: bitrix
  become: true
  vars:
    zabbix_server_address: 185.253.8.57
    listen_ip_address: "{{ansible_eth0.ipv4.address}}"
  roles:
    - deploy_zabbix
