---
- hosts: bitrix
  vars:
    - server_hostname: test.org
    - key_size: 4096
    - passphrase: # Set if you want passphrase
    - key_type: RSA # Others include DSA, ECC, Ed25519, Ed448, X25519, X448
    - country_name: KZ
    - email_address: admin@test.org
    - organization_name: Test
  tasks:
    - name: Generate an OpenSSL private key
      openssl_privatekey:
        path: "/home/bitrix/cert/{{ server_hostname }}_privkey.pem"
        size: "{{ key_size }}"
        type: "{{ key_type }}"
        backup: yes
    - name: Generate an OpenSSL Certificate Signing Request with Subject information
      openssl_csr:
        path: "/home/bitrix/cert/{{ server_hostname }}.csr"
        privatekey_path: "/home/bitrix/cert/{{ server_hostname }}_privkey.pem"
        country_name: "{{ country_name }}"
        organization_name: "{{ organization_name }}"
        email_address: "{{ email_address }}"
        common_name: "{{ server_hostname }}"
    - name: Generate a Self Signed OpenSSL certificate
      openssl_certificate:
        path: "/home/bitrix/cert/{{ server_hostname }}_cert.pem"
        privatekey_path: "/home/bitrix/cert/{{ server_hostname }}_privkey.pem"
        csr_path: "/home/bitrix/cert/{{ server_hostname }}.csr"
        provider: selfsigned

    - name: Creates a cron file under /etc/cron.d
      ansible.builtin.cron:
        name: yum autoupdate
        weekday: "2"
        minute: "0"
        hour: "12"
        user: root
        job: "YUMINTERACTIVE=0 /usr/sbin/yum-autoupdate"
        cron_file: ansible_yum-autoupdate
        state: absent    
