---
# tasks file for deploy_apache_web

- block:  # ===== Block for RedHat =====

    - name: Install Apache for RedHat
      yum: name=httpd state=latest

    - name: Generate my page
      template: src=index.j2  dest={{ dest }}/index.html  mode=0555
      notify: Restart Apache RedHat

    - name: Start my Webserver & enable on boot for RedHat
      service: name=httpd  state=started enabled=yes

  when: ansible_os_family == "RedHat"


- block:  # ===== Block for Debian =====

     - name: Install Apache for ubuntu
       apt: name=apache2 state=latest


     - name: Copy my page
       template: src=index.j2  dest={{ dest }}/index.html  mode=0555
       notify: Restart Apache Debian


     - name: Start my Webserver & enable on boot for Debian
       service: name=apache2  state=started enabled=yes

  when: ansible_os_family == "Debian"



- name: Copy Images
  copy: 
    src: "{{ item }}"  
    dest: "{{ dest }}" 
    mode: 0555
  loop:
    - "rus.png"
    - "kaz.png"
    - "ukr.png"

  notify:
      
    - Restart Apache RedHat
    - Restart Apache Debian
